name: Update README

on:
  schedule:
    - cron: "*/90 * * * *" # Update every 90 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Add activity to readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
